name: CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [11, 17, 19]
    name: Java ${{ matrix.java }} sample

    steps:
    - name: Checkout calimero-core
      uses: actions/checkout@v3
      with:
        repository: calimero-project/calimero-core
        path: calimero-core
    - name: Checkout calimero-usb
      uses: actions/checkout@v3
      with:
        repository: calimero-project/calimero-usb
        path: calimero-usb
    - name: setup
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
    - name: Setup Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
    - name: Execute Gradle build
      run: |
        cd calimero-usb
        ./gradlew build
